
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 3306

development:
  <<: *default
  password: <%= ENV['ROOT_PASSWORD'] %>
  host: '127.0.0.1'
  database: alliance_hackathon_development

production:
  <<: *default
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['ROOT_PASSWORD'] %>
  host: <%= ENV['DATABASE_URL'] %>
  database: alliance_hackathon