default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV["DB_POOL"] || 5  %>
  database: <%= ENV['DB_NAME'] || 'alliance_hackathon_development' %>
  username: <%= ENV['DB_USER'] || 'root' %>
  password: <%= ENV['ROOT_PASSWORD'] %>
  host: <%= ENV["DB_HOST"] %>
  url: <%= ENV['DATABASE_URL'] %> # takes higher precedence than other settings
  reconnect: true

development:
  <<: *default
  database: alliance_hackathon_production

test:
  <<: *default
  database: alliance_hackathon_test

production:
  <<: *default
  database: alliance_hackathon
  url: <%= ENV['DATABASE_URL'] %>
